name: progress_future
description: A Future that reports the progress of its completion, and various progress bars to show it in CLI.
version: 0.1.0
repository: https://github.com/alexeyinkin/dart-progress-future

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  async: ^2.11.0
  clock: ^1.1.1

dev_dependencies:
  matching: ^0.1.3
  print_buffer: ^0.1.1
  test: ^1.25.5
  total_lints: ^3.4.0

dependency_overrides:
  #print_buffer: { path: ../dart-print-buffer }
